# Use root/example as user/password credentials
version: '3.1'

networks:
  app-tier: 
    driver: bridge

services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: "mysql-container"
    networks:
      - app-tier
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
     - 'mysql_data:/var/lib/mysql'
  
  redis:
    image : redis:latest
    container_name: "redis-container"
    networks:
      - app-tier
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis"

volumes:
  redis_data:
    driver: local
  mysql_data:
    driver: local