# Use root/example as user/password credentials
version: '3.1'

networks:
  app-tier: 
    driver: bridge

services:

  sonarqube: 
    image: sonarqube:latest
    container_name: "sonarqube-container"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    depends_on:
      - sonar-db
    networks:
      - app-tier
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: "mysql-container"
    networks:
      - app-tier
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
     - 'mysql_data:/var/lib/mysql'

  sonar-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    networks:
      - app-tier
    ports:
      - "5432:5432"
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  redis:
    image : redis:latest
    container_name: "redis-container"
    networks:
      - app-tier
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis"

volumes:
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local
  redis_data:
    driver: local
  mysql_data:
    driver: local